
FROM node
EXPOSE 5000
WORKDIR /usr/src/app
COPY . .
RUN npm install && npm run build && \
    npm install -g serve && \
    useradd -m appuser && chown -R appuser .

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]