
FROM node
EXPOSE 5000
WORKDIR /usr/src/app
COPY . .
RUN npm install && npm run build
RUN npm install -g serve

# Add user
RUN useradd -m appuser
RUN chown -R appuser .
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]