version: '3'

services:

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/usr/local/etc/redis

  app-back:
    image: backend
    container_name: app-back
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
      
  app-front:
    image: frontend
    container_name: app-front
    ports:
      - 5000:5000
    
  db:
    image: postgres:13.2-alpine
    container_name: db_backend
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./database:/var/lib/postgresql/data