version: '3'

services:

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - 6379:6379

  app-back:
    image: backend
    container_name: app-back
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis

  app-front:
    image: frontend
    container_name: app-front
    ports:
      - 5000:5000