
FROM node:16-alpine3.11
EXPOSE 5000
WORKDIR /usr/src/app
COPY . .
RUN npm install && npm run build && \
    npm install -g serve && \
    adduser -D appuser

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]